#!/usr/bin/env python3
import json
from collections import defaultdict
from pathlib import Path

from jsonschema import Draft202012Validator, FormatChecker


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "data/evals/problem_cases.schema.json"
JSONL_PATH = ROOT / "data/evals/problem_cases.jsonl"
OUTPUT_PATH = ROOT / "docs/PROBLEM-CASES.md"

SEVERITY_ORDER = ["high", "med", "low"]


def slugify(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")


def load_schema() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_cases(schema: dict) -> list[dict]:
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    cases = []
    with JSONL_PATH.open("r", encoding="utf-8") as f:
        for i, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue
            try:
                case = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON on line {i}: {exc}") from exc

            errors = sorted(validator.iter_errors(case), key=lambda e: e.path)
            if errors:
                first = errors[0]
                path = ".".join(str(part) for part in first.path) or "<root>"
                raise ValueError(
                    f"Schema validation failed on line {i} at {path}: {first.message}"
                )
            cases.append(case)
    return cases


def render(cases: list[dict]) -> str:
    by_severity = defaultdict(list)
    by_tag = defaultdict(list)

    for case in cases:
        by_severity[case["severity"]].append(case)
        for tag in case["tags"]:
            by_tag[tag].append(case)

    sorted_cases = sorted(cases, key=lambda c: (SEVERITY_ORDER.index(c["severity"]), c["id"]))

    lines = [
        "# Problem Cases",
        "",
        "_Generated by `scripts/render_problem_cases.py` from `data/evals/problem_cases.jsonl`. Do not edit manually._",
        "",
        "## Table of Contents",
        "",
        "### By Severity",
    ]

    for sev in SEVERITY_ORDER:
        cases_for_sev = sorted(by_severity.get(sev, []), key=lambda c: c["id"])
        if not cases_for_sev:
            continue
        lines.append(f"- `{sev}`")
        for case in cases_for_sev:
            anchor = slugify(f"{case['id']}-{case['title']}")
            lines.append(f"  - [{case['id']}: {case['title']}](#{anchor})")

    lines.extend(["", "### By Tag"])
    for tag in sorted(by_tag):
        tag_cases = sorted(by_tag[tag], key=lambda c: c["id"])
        links = []
        for case in tag_cases:
            anchor = slugify(f"{case['id']}-{case['title']}")
            links.append(f"[`{case['id']}`](#{anchor})")
        linked = ", ".join(links)
        lines.append(f"- `{tag}`: {linked}")

    lines.append("")
    for case in sorted_cases:
        lines.append(f"## {case['id']}: {case['title']}")
        lines.append("")
        lines.append(f"- Created: `{case['created_at']}`")
        lines.append(f"- Severity: `{case['severity']}`")
        lines.append(f"- Tags: {', '.join(f'`{tag}`' for tag in case['tags'])}")
        lines.append("")
        lines.append("### Context")
        lines.append(case["context"])
        lines.append("")
        lines.append("### User Ask")
        lines.append(case["user_ask"])
        lines.append("")
        lines.append("### Observed Bad")
        lines.append(case["observed_bad"])
        lines.append("")
        lines.append("### Expected Good")
        lines.append(case["expected_good"])
        if "notes" in case and case["notes"]:
            lines.append("")
            lines.append("### Notes")
            lines.append(case["notes"])
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    schema = load_schema()
    cases = load_cases(schema)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(cases), encoding="utf-8")


if __name__ == "__main__":
    main()
